/**
 * Generate `src/styles/tokens.css` from `src/tokens.ts`.
 *
 * Run: `bun run tokens:build`.
 *
 * Output is deterministic (no timestamps, stable key order), so re-running on an
 * unchanged `tokens.ts` produces byte-identical CSS — the Phase 1 gate.
 *
 * Theme-independent tokens live in the default `:root, [data-theme='dark']` block
 * and are inherited by `[data-theme='light']`; only themed tokens are redefined
 * under light.
 */

import type { Themed } from '../src/tokens'
import {
  colors,
  fontSizes,
  fonts,
  fontWeights,
  leading,
  motion,
  radius,
  shadows,
  space,
  tracking,
  zIndex,
} from '../src/tokens'

const PREFIX = '--sk-'

/** `[cssVarName, value]` pairs. */
type Decl = readonly [string, string]

const decl = (name: string, value: string | number): Decl => [`${PREFIX}${name}`, String(value)]

/** Flatten a static (theme-independent) group into declarations, one per key. */
function staticGroup(prefix: string, group: Record<string, string | number>): Decl[] {
  return Object.entries(group).map(([key, value]) => decl(`${prefix}${key}`, value))
}

/** Split a themed group into its dark and light declarations. */
function themedGroup(
  prefix: string,
  group: Record<string, Themed>,
): { dark: Decl[]; light: Decl[] } {
  const dark: Decl[] = []
  const light: Decl[] = []
  for (const [key, value] of Object.entries(group)) {
    dark.push(decl(`${prefix}${key}`, value.dark))
    light.push(decl(`${prefix}${key}`, value.light))
  }
  return { dark, light }
}

const themedColors = themedGroup('', colors)
const themedShadows = themedGroup('shadow-', shadows)

/** Theme-independent declarations, grouped for readable output. */
const staticSections: Array<{ title: string; decls: Decl[] }> = [
  { title: 'Typography — families', decls: staticGroup('font-', fonts) },
  { title: 'Typography — size scale', decls: staticGroup('text-', fontSizes) },
  { title: 'Typography — weights', decls: staticGroup('weight-', fontWeights) },
  { title: 'Typography — tracking', decls: staticGroup('tracking-', tracking) },
  { title: 'Typography — leading', decls: staticGroup('leading-', leading) },
  { title: 'Spacing', decls: staticGroup('space-', space) },
  { title: 'Radius', decls: staticGroup('radius-', radius) },
  {
    title: 'Motion',
    decls: [...staticGroup('duration-', motion.duration), decl('ease', motion.ease)],
  },
  { title: 'Z-index', decls: staticGroup('z-', zIndex) },
]

const INDENT = '  '

function renderBlock(sections: Array<{ title: string; decls: Decl[] }>): string {
  const lines: string[] = []
  for (const section of sections) {
    lines.push(`${INDENT}/* ${section.title} */`)
    for (const [name, value] of section.decls) {
      lines.push(`${INDENT}${name}: ${value};`)
    }
    lines.push('')
  }
  // Drop the trailing blank line.
  if (lines.at(-1) === '') lines.pop()
  return lines.join('\n')
}

const header = [
  '/*',
  ' * GENERATED by scripts/build-tokens.ts — do not edit by hand.',
  ' * Source of truth: src/tokens.ts. Regenerate with `bun run tokens:build`.',
  ' */',
  '',
].join('\n')

const defaultBlock = renderBlock([
  { title: 'Color', decls: themedColors.dark },
  { title: 'Elevation', decls: themedShadows.dark },
  ...staticSections,
])

const lightBlock = renderBlock([
  { title: 'Color', decls: themedColors.light },
  { title: 'Elevation', decls: themedShadows.light },
])

const css = `${header}
:root,
[data-theme='dark'] {
${defaultBlock}
}

[data-theme='light'] {
${lightBlock}
}
`

const outPath = new URL('../src/styles/tokens.css', import.meta.url)
await Bun.write(outPath, css)
console.log(`tokens.css written (${css.length} bytes)`)
