/**
 * Generate `src/styles/tokens.css` and `src/styles/theme.css` from `src/tokens.ts`.
 *
 * Run: `bun run tokens:build`.
 *
 * - `tokens.css`: the raw `--sk-*` custom properties (dark default + light). Plain CSS,
 *   works with or without Tailwind (the fallback / raw path, Storybook, index.css).
 * - `theme.css`: the same palettes PLUS the Tailwind v4 `@theme inline` mapping
 *   (`--color-*` → `var(--sk-*)`, etc.) and the `bg-gradient-accent` `@utility`. Self-contained
 *   so a Tailwind consumer imports only this. `inline` keeps utilities pointing at the runtime
 *   `--sk-*` var, so `data-theme` switches colors with no `dark:` variant.
 *
 * Output is deterministic (no timestamps, stable key order), so re-running on an unchanged
 * `tokens.ts` produces byte-identical CSS — the Phase 1 gate.
 *
 * Theme-independent tokens live in the default `:root, [data-theme='dark']` block and are
 * inherited by `[data-theme='light']`; only themed tokens are redefined under light.
 */

import type { Themed } from '../src/tokens'
import {
  colors,
  fontSizes,
  fonts,
  fontWeights,
  leading,
  motion,
  radius,
  shadows,
  space,
  tracking,
  zIndex,
} from '../src/tokens'

const PREFIX = '--sk-'

/** `[cssVarName, value]` pairs. */
type Decl = readonly [string, string]

const decl = (name: string, value: string | number): Decl => [`${PREFIX}${name}`, String(value)]

/** Flatten a static (theme-independent) group into declarations, one per key. */
function staticGroup(prefix: string, group: Record<string, string | number>): Decl[] {
  return Object.entries(group).map(([key, value]) => decl(`${prefix}${key}`, value))
}

/** Split a themed group into its dark and light declarations. */
function themedGroup(
  prefix: string,
  group: Record<string, Themed>,
): { dark: Decl[]; light: Decl[] } {
  const dark: Decl[] = []
  const light: Decl[] = []
  for (const [key, value] of Object.entries(group)) {
    dark.push(decl(`${prefix}${key}`, value.dark))
    light.push(decl(`${prefix}${key}`, value.light))
  }
  return { dark, light }
}

const themedColors = themedGroup('', colors)
const themedShadows = themedGroup('shadow-', shadows)

/** Theme-independent declarations, grouped for readable output. */
const staticSections: Array<{ title: string; decls: Decl[] }> = [
  { title: 'Typography — families', decls: staticGroup('font-', fonts) },
  { title: 'Typography — size scale', decls: staticGroup('text-', fontSizes) },
  { title: 'Typography — weights', decls: staticGroup('weight-', fontWeights) },
  { title: 'Typography — tracking', decls: staticGroup('tracking-', tracking) },
  { title: 'Typography — leading', decls: staticGroup('leading-', leading) },
  { title: 'Spacing', decls: staticGroup('space-', space) },
  { title: 'Radius', decls: staticGroup('radius-', radius) },
  {
    title: 'Motion',
    decls: [...staticGroup('duration-', motion.duration), decl('ease', motion.ease)],
  },
  { title: 'Z-index', decls: staticGroup('z-', zIndex) },
]

const INDENT = '  '

function renderBlock(sections: Array<{ title: string; decls: Decl[] }>): string {
  const lines: string[] = []
  for (const section of sections) {
    lines.push(`${INDENT}/* ${section.title} */`)
    for (const [name, value] of section.decls) {
      lines.push(`${INDENT}${name}: ${value};`)
    }
    lines.push('')
  }
  // Drop the trailing blank line.
  if (lines.at(-1) === '') lines.pop()
  return lines.join('\n')
}

const header = [
  '/*',
  ' * GENERATED by scripts/build-tokens.ts — do not edit by hand.',
  ' * Source of truth: src/tokens.ts. Regenerate with `bun run tokens:build`.',
  ' */',
  '',
].join('\n')

const defaultBlock = renderBlock([
  { title: 'Color', decls: themedColors.dark },
  { title: 'Elevation', decls: themedShadows.dark },
  ...staticSections,
])

const lightBlock = renderBlock([
  { title: 'Color', decls: themedColors.light },
  { title: 'Elevation', decls: themedShadows.light },
])

const paletteCss = `:root,
[data-theme='dark'] {
${defaultBlock}
}

[data-theme='light'] {
${lightBlock}
}
`

const tokensCss = `${header}${paletteCss}`

// --- theme.css: palettes + Tailwind @theme inline mapping ---------------------------

/** `--<tw>: var(--sk-<sk>)` mapping line. */
const mapLine = (twName: string, skName: string) => `${INDENT}${twName}: var(--sk-${skName});`

function mapGroup(twPrefix: string, keys: string[], skPrefix = twPrefix): string {
  return keys.map((k) => mapLine(`${twPrefix}${k}`, `${skPrefix}${k}`)).join('\n')
}

// Colors map to the Tailwind `--color-*` namespace, except the gradient (a `@utility`).
const colorKeys = Object.keys(colors).filter((k) => k !== 'gradient-accent')

const themeInline = [
  `${INDENT}/* Colors → bg-*, text-*, border-*, ring-* */`,
  mapGroup('--color-', colorKeys, ''),
  '',
  `${INDENT}/* Font families → font-* */`,
  mapGroup('--font-', Object.keys(fonts), 'font-'),
  '',
  `${INDENT}/* Font sizes → text-* */`,
  mapGroup('--text-', Object.keys(fontSizes), 'text-'),
  '',
  `${INDENT}/* Line-height → leading-* */`,
  mapGroup('--leading-', Object.keys(leading), 'leading-'),
  '',
  `${INDENT}/* Letter-spacing → tracking-* */`,
  mapGroup('--tracking-', Object.keys(tracking), 'tracking-'),
  '',
  `${INDENT}/* Radius → rounded-* */`,
  mapGroup('--radius-', Object.keys(radius), 'radius-'),
  '',
  `${INDENT}/* Shadow → shadow-* */`,
  mapGroup('--shadow-', Object.keys(shadows), 'shadow-'),
  '',
  `${INDENT}/* Motion → duration-*, ease-sukuna */`,
  mapGroup('--duration-', Object.keys(motion.duration), 'duration-'),
  `${INDENT}--ease-sukuna: var(--sk-ease);`,
].join('\n')

const themeCss = `${header}${paletteCss}
@theme inline {
${themeInline}
}

@utility bg-gradient-accent {
  background-image: var(--sk-gradient-accent);
}
`

await Bun.write(new URL('../src/styles/tokens.css', import.meta.url), tokensCss)
await Bun.write(new URL('../src/styles/theme.css', import.meta.url), themeCss)
console.log(`tokens.css (${tokensCss.length} B) + theme.css (${themeCss.length} B) written`)
